[package]
name = "sort"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.19.0"
nannou_egui = "0.19.0"
random = "0.14.0"
strum = "0.27.1"
strum_macros = "0.27.1"
